# Generated by Django 3.0.5 on 2021-08-10 13:10

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.CharField(max_length=255)),
                ('condition', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vl_rate', models.IntegerField()),
                ('l_rate', models.IntegerField()),
                ('m_rate', models.IntegerField()),
                ('h_rate', models.IntegerField()),
                ('vh_rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=255)),
                ('ram', models.IntegerField()),
                ('cpu', models.IntegerField()),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('architecture', models.CharField(max_length=30)),
                ('costEstimation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_application', models.CharField(max_length=30)),
                ('environment', models.CharField(max_length=30)),
                ('sla', models.IntegerField()),
                ('dependencies', jsonfield.fields.JSONField(default=dict)),
                ('flux', jsonfield.fields.JSONField(default=dict)),
                ('data_size', models.IntegerField()),
                ('cpu', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('owner', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('flexibility', models.IntegerField()),
                ('maturity', models.IntegerField()),
                ('data_security', models.IntegerField()),
                ('reliability', models.IntegerField()),
                ('price', models.IntegerField()),
                ('geo_dispatching', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('criticality', models.IntegerField()),
                ('complexity', models.IntegerField()),
                ('availability', models.IntegerField()),
                ('type', models.CharField(max_length=30)),
                ('contraint', models.DecimalField()),
            ],
        ),
    ]
