# Generated by Django 3.0.5 on 2021-05-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atom',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
