# Generated by Django 3.0.5 on 2021-06-10 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root_app', '0002_auto_20210528_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cond1', models.CharField(max_length=255)),
                ('value1', models.IntegerField()),
                ('cond2', models.CharField(max_length=255)),
                ('value2', models.IntegerField()),
                ('cond3', models.CharField(max_length=255)),
                ('value3', models.IntegerField()),
                ('cond4', models.CharField(max_length=255)),
                ('value4', models.IntegerField()),
                ('cond5', models.CharField(max_length=255)),
                ('value5', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='atom',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='atom',
            name='complexity',
        ),
        migrations.RemoveField(
            model_name='atom',
            name='criticality',
        ),
        migrations.AddField(
            model_name='atom',
            name='criteria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='root_app.Criteria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rule',
            name='type',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='atom',
            name='condition',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='root_app.Condition'),
            preserve_default=False,
        ),
    ]
