# Generated by Django 3.0.5 on 2021-08-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_app', '0003_auto_20210810_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='contraint',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
