# Generated by Django 3.0.5 on 2021-06-10 02:48

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('root_app', '0003_auto_20210610_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='cond1',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='cond2',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='cond3',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='cond4',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='cond5',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='value1',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='value2',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='value3',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='value4',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='value5',
        ),
        migrations.AddField(
            model_name='condition',
            name='condition',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
