# Generated by Django 3.0.5 on 2021-06-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_app', '0004_auto_20210610_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='atom',
            name='status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
