# Generated by Django 3.0.5 on 2021-08-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_app', '0004_auto_20210810_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='contraint',
            field=models.IntegerField(),
        ),
    ]
