# Generated by Django 3.0.5 on 2021-08-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_app', '0005_auto_20210810_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='contraint',
            field=models.IntegerField(default=20),
        ),
    ]
