# Generated by Django 3.0.5 on 2021-06-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_app', '0006_auto_20210624_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
