# Generated by Django 3.0.5 on 2021-08-10 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root_app', '0006_auto_20210810_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='contraint',
        ),
    ]
