# Generated by Django 3.0.5 on 2021-06-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_app', '0007_auto_20210624_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='data_security',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='flexibility',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='geo_dispatching',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='maturity',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='price',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='reliability',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attribute',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=4),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProviderAttribute',
        ),
    ]
