# Generated by Django 3.0.5 on 2021-08-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_app', '0007_remove_rule_contraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='contraint',
            field=models.IntegerField(default=20),
        ),
    ]
