# Generated by Django 3.0.5 on 2021-06-24 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root_app', '0008_auto_20210624_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atom',
            name='criteria',
        ),
    ]
