# Generated by Django 3.0.5 on 2021-06-25 12:02

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('root_app', '0009_remove_atom_criteria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atom',
            name='status',
        ),
        migrations.AddField(
            model_name='atom',
            name='criteria',
            field=models.CharField(default=2, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atom',
            name='condition',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
