# Generated by Django 3.0.5 on 2021-06-25 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root_app', '0010_auto_20210625_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atom',
            name='name',
        ),
    ]
