# Generated by Django 3.0.5 on 2021-06-26 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root_app', '0011_remove_atom_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='percentage',
        ),
    ]
