# Generated by Django 3.0.5 on 2021-06-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_app', '0012_remove_attribute_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='cpu',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='ram',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
