# Generated by Django 3.0.5 on 2021-06-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_app', '0013_auto_20210626_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='ram',
        ),
        migrations.AddField(
            model_name='project',
            name='cpu',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='ram',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
